name: BubbleReset
main: com.bubblecraft.bubblereset.BubbleReset
version: ${project.version}
description: High-Performance Resource World plugin for Minecraft 1.19-1.21
author: eirvi
api-version: 1.19
depend: []
softdepend: [PlaceholderAPI]
commands:
  resource:
    description: Main resource world command - opens menu when used without arguments
    usage: /resource [tp|menu|reset|reload] [world]
    aliases: [rw, resourceworld]
  rwadmin:
    description: Admin commands for BubbleReset
    usage: /rwadmin [panel|reload|test]
    aliases: [rwa]
permissions:
  rw.tp:
    description: Access to teleport to resource world
    default: true
  # Legacy nodes no longer required but kept for compatibility
  rw.tp.nether:
    description: (Legacy) Access to teleport to resource nether
    default: true
  rw.tp.end:
    description: (Legacy) Access to teleport to resource end
    default: true
  rw.admin:
    description: Access to admin commands
    default: op
  rw.menu:
    description: Access to resource world menu
    default: true
